CC=m68k-amigaos-gcc
ASS=vasmm68k_mot
LINK=vlink
STRIP=m68k-amigaos-strip

#find the toolchain's directory
PREFIX = $(shell ./getprefix.sh "$(CC)")

DEV = 1

AFLAGS = -Fhunk -m68060 -linedebug -chklabels -align -L listing.txt -DDEV=${DEV} -Dmnu_nocode=1

AFLAGS += -I../ \
		  -I$(PREFIX)/m68k-amigaos/ndk-include \
		  -I../media \
		  -I../media/includes

LFLAGS = -b amigahunk -sc -l amiga -L $(PREFIX)m68k-amigaos/ndk/lib/libs

all:	 hires

clean:
	rm *.o

%:	%.s Makefile.dev
	$(ASS) $(AFLAGS) -o $@.o $<
	$(LINK) $(LFLAGS) $@.o -o $@

%.o:	%.c Makefile.dev
	$(CC) $(CFLAGS) -c $< -o $@

%_stripped:	%
	$(STRIP) --strip-debug --strip-unneeded -o $@ $< 

#############################################################
#
#############################################################
