#ifndef DEFS_H
#define DEFS_H

#include <exec/types.h>

/**
 * C structure definitions to match the assembler ones in defs.i
 *
 * DO NOT EDIT THIS FILE WITHOUT MAKING THE CORRESPONDING CHANGES IN defs.i
 */

#define MAX_LEVEL_OBJ_DIST_COUNT    (256+32)
#define MAX_OBJS_IN_LINE_COUNT      400
#define LVL_OBJ_DEFINITION_SIZE     64

#define NUM_LEVELS          16
#define NUM_BULLET_DEFS     20
#define NUM_GUN_DEFS        10
#define NUM_ALIEN_DEFS      20
#define NUM_OBJECT_DEFS     30
#define NUM_SFX             64
#define NUM_WALL_TEXTURES   16

/**
 * Collectable Counts
 *
 * This structure is used in many larger aggregates
 */
typedef struct {
    UWORD cc_Health;
    UWORD cc_JetpackFuel;
    UWORD cc_AmmoCounts[NUM_BULLET_DEFS];
}  __attribute__((packed)) CollectableCounts;

/**
 * Inventory
 *
 * Used by player and collectable items
 */
typedef struct {
    /* For compatibility with the assembler code, there must be no alignment gaps */
    CollectableCounts inv_Counts;
    UWORD inv_Shield;
    UWORD inv_Jetpack;
    UWORD inv_Weapons[NUM_GUN_DEFS];
} __attribute__((packed)) Inventory;


#endif // DEFS_H
