#ifndef PREFS_KEYS_H
#define PREFS_KEYS_H

    /* Keybinding GFCOptions */
    {
        "key.turn_left",
        &Prefs_AssignableKeys_vb[KEY_TURN_LEFT],
        CFG_PARAM_TYPE_KEY,
        CFG_VAR_TYPE_UBYTE
    },
    {
        "key.turn_right",
        &Prefs_AssignableKeys_vb[KEY_TURN_RIGHT],
        CFG_PARAM_TYPE_KEY,
        CFG_VAR_TYPE_UBYTE
    },
    {
        "key.forwards",
        &Prefs_AssignableKeys_vb[KEY_FORWARDS],
        CFG_PARAM_TYPE_KEY,
        CFG_VAR_TYPE_UBYTE
    },
    {
        "key.backwards",
        &Prefs_AssignableKeys_vb[KEY_BACKWARDS],
        CFG_PARAM_TYPE_KEY,
        CFG_VAR_TYPE_UBYTE
    },
    {
        "key.fire",
        &Prefs_AssignableKeys_vb[KEY_FIRE],
        CFG_PARAM_TYPE_KEY,
        CFG_VAR_TYPE_UBYTE
    },
    {
        "key.use",
        &Prefs_AssignableKeys_vb[KEY_USE],
        CFG_PARAM_TYPE_KEY,
        CFG_VAR_TYPE_UBYTE
    },
    {
        "key.run",
        &Prefs_AssignableKeys_vb[KEY_RUN],
        CFG_PARAM_TYPE_KEY,
        CFG_VAR_TYPE_UBYTE
    },
    {
        "key.side_step",
        &Prefs_AssignableKeys_vb[KEY_FORCE_SIDESTEP],
        CFG_PARAM_TYPE_KEY,
        CFG_VAR_TYPE_UBYTE
    },
    {
        "key.step_left",
        &Prefs_AssignableKeys_vb[KEY_STEP_LEFT],
        CFG_PARAM_TYPE_KEY,
        CFG_VAR_TYPE_UBYTE
    },
    {
        "key.step_right",
        &Prefs_AssignableKeys_vb[KEY_STEP_RIGHT],
        CFG_PARAM_TYPE_KEY,
        CFG_VAR_TYPE_UBYTE
    },
    {
        "key.duck",
        &Prefs_AssignableKeys_vb[KEY_DUCK],
        CFG_PARAM_TYPE_KEY,
        CFG_VAR_TYPE_UBYTE
    },
    {
        "key.look_behind",
        &Prefs_AssignableKeys_vb[KEY_LOOK_BEHIND],
        CFG_PARAM_TYPE_KEY,
        CFG_VAR_TYPE_UBYTE
    },
    {
        "key.jump",
        &Prefs_AssignableKeys_vb[KEY_JUMP],
        CFG_PARAM_TYPE_KEY,
        CFG_VAR_TYPE_UBYTE
    },
    {
        "key.look_up",
        &Prefs_AssignableKeys_vb[KEY_LOOK_UP],
        CFG_PARAM_TYPE_KEY,
        CFG_VAR_TYPE_UBYTE
    },
    {
        "key.look_down",
        &Prefs_AssignableKeys_vb[KEY_LOOK_DOWN],
        CFG_PARAM_TYPE_KEY,
        CFG_VAR_TYPE_UBYTE
    },
    {
        "key.centre_look",
        &Prefs_AssignableKeys_vb[KEY_CENTRE_VIEW],
        CFG_PARAM_TYPE_KEY,
        CFG_VAR_TYPE_UBYTE
    },
    {
        "key.next_weapon",
        &Prefs_AssignableKeys_vb[KEY_NEXT_WEAPON],
        CFG_PARAM_TYPE_KEY,
        CFG_VAR_TYPE_UBYTE
    },

#endif // PREFS_KEYS_H
